name: Deploy to GitHub Pages

on:
    push:
        branches: ['master']
    workflow_dispatch: # Позволяет запускать деплой вручную из вкладки Actions

# Устанавливаем права для деплоя
permissions:
    contents: read
    pages: write
    id-token: write

# Ограничиваем количество одновременных деплоев
concurrency:
    group: 'pages'
    cancel-in-progress: false

jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22' # Укажите вашу версию Node.js

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build # Команда сборки из вашего package.json

            - name: Setup Pages
              uses: actions/configure-pages@v4

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: './dist' # ИЛИ './build' - Укажите папку с результатом сборки
                  # Важно! Это должна быть та самая папка, которую создает команда 'npm run build'

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
